---
- hosts: all

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - include_tasks: tasks/kamailio.yml
