---
- name: Add keys for Kamailio repo
  apt_key:
    url: http://deb.kamailio.org/kamailiodebkey.gpg
    state: present
  become: true

- name: Add repo to sources.list
  apt_repository:
    repo: deb http://deb.kamailio.org/kamailio{{kamailio_version}} {{hostvars[inventory_hostname]['ansible_lsb']['codename']}} main
    state: present
  become: true

- name: Install Kamailio
  # Updates cache (apt-get update) and then installs Kamailio
  apt:
    name: kamailio
    update_cache: yes
    state: present
  register: kamailio_installed_firstrun
  become: true

- name: Start Kamailio if installed for the first time
  service:
    name: kamailio
    state: started
  when: kamailio_installed_firstrun.changed
  become: true

  